version: '3.4'

services:
  dgab.authentication.host:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7012
      
    # ports:
    #   - "80"
    #   - "443"
    volumes:
      # - ${USERPROFILE}\.aspnet\https:/https/
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  